# Generated by Django 3.2.9 on 2021-11-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
